### ISSUE TITLE
Add smooth transition when user hovers over profile cards.

### ISSUE THREAD

**Issue by abitsalihu** [BVPIEEE/bvpieee-frontend#11]
Add a smooth transition when the user `hovers` over the profile cards.

Below is the video of the current state of the profile cards when `hovered`:

https://user-images.githubusercontent.com/94648837/195167100-946388f4-ce8e-4df4-9789-531fd6fe8ce0.mov

The expected behaviour should make the transition go smoothly in and out.

To whoever is fixing this it should be resolved by adding  ```transition: all .2s ease;``` in the container to which the `hovered` state is added. :)

**Comment by anubhav06** [comment]
Go ahead @abitsalihu :)
