### ISSUE TITLE
Correct an image in About Us page 

### ISSUE THREAD

**Issue by AK-shat-JAIN** [BVPIEEE/bvpieee-frontend#19]
Among one of the last image is not perfect circle correct it and attach a screenshot of corrected one

**Comment by tomoyanime** [comment]
Hi @AK-shat-JAIN I can work on this. Is it the image of Abhay Tiwari?

**Comment by Ankit-0009** [comment]
Can I work on it?

**Comment by AK-shat-JAIN** [comment]
@tomoyanime , its image of Bhavya
