### ISSUE TITLE
FEATURE 🚀: Navbar - Contact US

### ISSUE THREAD

**Issue by anubhav06** [BVPIEEE/bvpieee-frontend#5]
When a user clicks  on "Contact Us" button, then it should scroll down to the footer.    

![1](https://user-images.githubusercontent.com/43821031/194926850-c4d7555b-d8ef-4b13-a003-ebb44074a733.png)

**Comment by abitsalihu** [comment]
Hey @anubhav06, I would like to work on this issue. :)

**Comment by anubhav06** [comment]
Sure, go ahead @abitsalihu :)

**Comment by anubhav06** [comment]
Closes #7
