### ISSUE TITLE
FIX 🔨: Rename text to IEEE

### ISSUE THREAD

**Issue by anubhav06** [BVPIEEE/bvpieee-frontend#6]
The text in footer needs to be renamed to IEEE from IEE.
This needs to be done in the following pages:
1. home page
2. community page

![0](https://user-images.githubusercontent.com/43821031/195112413-5281741f-547d-46be-92e8-df3ff9672fa5.png)

**Comment by hemantwasthere** [comment]
@anubhav06 I would like to work on this issue

**Comment by anubhav06** [comment]
Sure @hemantwasthere, go ahead

**Comment by hemantwasthere** [comment]
Hey @anubhav06, I have opened PR #14, Please have a look
