### ISSUE TITLE
Change the active link in the navbar when the user navigates it

### ISSUE THREAD

**Issue by abitsalihu** [BVPIEEE/bvpieee-frontend#9]
The active link does not change when the user navigates in the navbar.(The `Home` link is always the `blue:active-looking` one)

Below is a video of the bug:

https://user-images.githubusercontent.com/94648837/195160313-6fc9fbb9-d390-4adb-8099-c112ea4c384b.mov

I would like to work on this issue if possible. :)

**Comment by anubhav06** [comment]
Go ahead @abitsalihu
